# Generated by Django 5.0.6 on 2024-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoneyDebt',
        ),
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
